---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  - en_US
  - bash
  - words
  - python
  - python-common
enabled: true
useGitignore: true
ignorePaths:
  - cspell.config.yaml
  - ./samples/integration/*.*
  # Other
  - "*.svg"
  - ".vscode/**"
