[project]
name = "mk-pre"
version = "0.1.0"
description = "mk-pre plugin"
readme = "README.md"
requires-python = ">=3.11.0"
authors = [{ name = "Sorin Sbarnea", email = "sorin.sbarnea@gmail.com" }]
dependencies = [
  "rich>=12.0.0",  # indirect of typer/tox
  "typer>=0.16.0",  # indirect of typer/tox
  "typer-config>=1.4.2",
  "typing-extensions>=4.14.1",  # indirect of typer/tox
]

[project.entry-points."mk_tools"]
pre = "mk_pre.pre:PreTool"

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"
