[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.8.6,<0.9.0"]

[project]
authors = [{email = "sorin.sbarnea@gmail.com", name = "Sorin Sbarnea"}]
dependencies = [
  "rich>=12.0.0",
  "typer>=0.16.0",
  "typer-config>=1.4.2",
  "typing-extensions>=4.14.1" # indirect of typer/tox
]
description = "mk-pre plugin"
name = "mk-pre"
readme = "README.md"
requires-python = ">=3.10.0"
version = "0.1.0"

[project.entry-points."mk_tools"]
pre = "mk_pre.pre:PreTool"
